In [1]:
import pandas as pd
import numpy as np

In [2]:
fd_pt1 = pd.read_csv('../dataset/raw_world_bank_pt1.csv')
fd_pt2 = pd.read_csv('../dataset/raw_world_bank_pt2.csv')
fd_pt3 = pd.read_csv('../dataset/raw_world_bank_pt3.csv')
fd_pt4 = pd.read_csv('../dataset/raw_world_bank_pt4.csv')
fd_pt5 = pd.read_csv('../dataset/raw_world_bank_pt5.csv')
fd_pt6 = pd.read_csv('../dataset/raw_world_bank_pt6.csv')
fd_pt7 = pd.read_csv('../dataset/raw_world_bank_pt7.csv')
fd_pt8 = pd.read_csv('../dataset/raw_world_bank_pt8.csv')
fd_pt9 = pd.read_csv('../dataset/raw_world_bank_pt9.csv')
fd_pt10 = pd.read_csv('../dataset/raw_world_bank_pt10.csv')

fd = pd.concat([fd_pt1, fd_pt2, fd_pt3, fd_pt4, fd_pt5, fd_pt6, fd_pt7, fd_pt8, fd_pt9, fd_pt10], ignore_index=True)


# Para comprobar que ha funcionado
fd.head()

,Country Name,Country Code,Series Name,Series Code,Time,Time Code,Value
0,Afghanistan,AFG,Multidimensional poverty headcount ratio (UNDP...,SI.POV.MPUN,1960.0,YR1960,NaN
1,Afghanistan,AFG,Multidimensional poverty headcount ratio (UNDP...,SI.POV.MPUN,1961.0,YR1961,NaN
2,Afghanistan,AFG,Multidimensional poverty headcount ratio (UNDP...,SI.POV.MPUN,1962.0,YR1962,NaN
3,Afghanistan,AFG,Multidimensional poverty headcount ratio (UNDP...,SI.POV.MPUN,1963.0,YR1963,NaN
4,Afghanistan,AFG,Multidimensional poverty headcount ratio (UNDP...,SI.POV.MPUN,1964.0,YR1964,NaN

In [4]:
fd.tail()

,Country Name,Country Code,Series Name,Series Code,Time,Time Code,Value
1591635,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1591636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1591637,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1591638,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN
1591639,Last Updated: 07/13/2026,NaN,NaN,NaN,NaN,NaN,NaN